version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ambassador
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 54322:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379



